import Head from 'next/head';
import Button from '../components/ui/Button';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 className="text-red-500 underline">Hi</h1>
          <Button />
        </div>
      </main>
    </div>
  );
}
